### ISSUE TITLE
cp: can't create '@***:~/': No such file or directory

### ISSUE THREAD

**Issue by kojofosu-ghyrate** [marcodallasanta/ssh-scp-deploy#13]
why do i keep getting this error please. any help?

**Comment by marcodallasanta** [comment]
Hi @kojofosu-ghyrate , could you please add your configuration to reproduce this?

**Comment by kojofosu-ghyrate** [comment]
```yml
      - name: Deploy snapshot
        uses: marcodallasanta/ssh-scp-deploy@v1.0.4
        with:
          local: './target/ServerLookup-1.0-SNAPSHOT.jar'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '~/'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.HOST}}                                      # Remote server address - REQUIRED true
          port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
          user: ${{secrets.USER}}                                      # Remote server user - REQUIRED true
          password: ${{secrets.PASSWORD}}     
```
