### ISSUE TITLE
Why say '🔑 Please provide at least a key or a password...'

### ISSUE THREAD

**Issue by fembiba** [marcodallasanta/ssh-scp-deploy#9]
```
name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: marcodallasanta/ssh-scp-deploy@839788b727a74baa1568028de752145c836b8acc
      with:
        local: './'
        remote: ${{ secrets.PROJECT_PATH }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}

**Comment by marcodallasanta** [comment]
Hi @rovecode. You  shoudl use the last version, the previous could be unstable or contain issues. 
Today I will release version 1.0.3 which will close another issue related to the user to perform scp.

So I suggest you to use: 

``` yml
- uses: marcodallasanta/ssh-scp-deploy@1.0.3
```

**Comment by marcodallasanta** [comment]
Hi @rovecode, I'm  checking out this issue. I'll resolve ASAP.

**Comment by choudharyhimanshu** [comment]
Hey @marcodallasanta, I am still facing this issue with the below config:

```
name: Deploy to DEV server
uses: marcodallasanta/ssh-scp-deploy@main
env:
    host: ${{ secrets.REMOTE_HOST }}
    user: ${{ secrets.REMOTE_USER }}
    password: ${{ secrets.REMOTE_PASS }}
    ssh_options: "-rltgoDzvO"
    local: "build/"
    remote: ${{ secrets.REMOTE_TARGET }}
```

Thanks in advance for your help!

**Comment by marcodallasanta** [comment]
Hi @choudharyhimanshu, this seems kind of strange. The issue seems to be  fixed, that was just a wrong variable used in a check as you can see here: https://github.com/marcodallasanta/ssh-scp-deploy/pull/11/files.

Checking i see you are using `marcodallasanta/ssh-scp-deploy@main`, I suggest you to use `@v1.0.4` or `latest`, and I'm sure you checked but I have to ask this, did you check your github secrets to have the right value and/or naming?

**Comment by marcodallasanta** [comment]
@choudharyhimanshu And maybe I don't have enough info about what are you doing, but I expect this:

```
uses: marcodallasanta/ssh-scp-deploy@latest
      with:
        local: 'build/'
        remote: ${{ secrets.PROJECT_PATH }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
```

Instead of:

```
uses: marcodallasanta/ssh-scp-deploy@main
env:
    host: ${{ secrets.REMOTE_HOST }}
    user: ${{ secrets.REMOTE_USER }}
    password: ${{ secrets.REMOTE_PASS }}
    ssh_options: "-rltgoDzvO"
    local: "build/"
    remote: ${{ secrets.REMOTE_TARGET }}
```

Let me know if this helped.
